// <auto-generated />
using System;
using Ensek.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ensek.DataAccess.Migrations
{
    [DbContext(typeof(EnsekDbContext))]
    partial class EnsekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ensek.DataAccess.DbModels.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1234,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9010), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Freya",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1239,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9100), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Noddy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1240,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9210), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Archie",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1241,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9230), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Lara",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1242,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9240), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tim",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1243,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9260), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Graham",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1244,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9270), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tony",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1245,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9290), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Neville",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1246,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9300), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Jo",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1247,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9310), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Jim",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1248,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9330), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Pam",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2233,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9340), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Barry",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2344,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9350), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tommy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2345,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9370), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Jerry",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2346,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9380), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Ollie",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2347,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9390), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tara",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2348,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9410), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tammy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2349,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9420), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Simon",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2350,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9430), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Colin",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2351,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9450), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Gladys",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2352,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9460), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Greg",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2353,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9470), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Tony",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2355,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9490), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Arthur",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2356,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9500), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Craig",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 4534,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9510), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "JOSH",
                            LastName = "TEST"
                        },
                        new
                        {
                            Id = 6776,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9520), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Laura",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 8766,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 10, 24, 10, 54, 13, 167, DateTimeKind.Unspecified).AddTicks(9630), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Sally",
                            LastName = "Test"
                        });
                });

            modelBuilder.Entity("Ensek.DataAccess.DbModels.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReadingDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ReadingValue")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("Ensek.DataAccess.DbModels.MeterReading", b =>
                {
                    b.HasOne("Ensek.DataAccess.DbModels.Account", null)
                        .WithMany("MeterReadings")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ensek.DataAccess.DbModels.Account", b =>
                {
                    b.Navigation("MeterReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
